name: dynamic_ogp_web_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ###  Routing  ###
  go_router: ^10.1.0
  ###  Web  ###
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
